# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test and coverage

on: [pull_request]

permissions:
  contents: read

jobs:
  test-coverage:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.4']
      fail-fast: true

    steps:
    - name: Install dependencies
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.6.4"
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Display Go version 
      run: go version
    - name: Intall pre-commit
      run: |
        pip install pre-commit
    - name: Run test with coverage
      run: |
        pre-commit run --all-files -v
    - name: Upload coverage reports to Codecov
      if: ${{ matrix.go-version }} == '1.21.4'
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        directory: ./build